runtime: java21
instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

env_variables:
  APP_BASE_URL: "https://trailblaze-460312.oa.r.appspot.com"

# Allow larger file uploads (50MB)
basic_scaling:
  max_instances: 5

# Configure handlers to properly serve uploaded photos
handlers:
# Static files handlers
- url: /uploads/photos/(.*)
  static_files: WEB-INF/uploads/photos/\1
  upload: WEB-INF/uploads/photos/.*
  secure: optional

# Application handlers (this should be last)
- url: /.*
  script: unused
  secure: optional
